# -*- coding: utf-8 -*-

# -------------------------------------------------------------------------------
# Memeo C1 Source Materials
#
# Copyright © 2016 UNICOM Systems, Inc. - A Division of UNICOM Global - All Rights Reserved
#
# Highly Confidential Material - All Rights Reserved
# -------------------------------------------------------------------------------

"""
This is a setup.py script generated by py2applet
Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['pJing.py']
APP_NAME = "pJing"
DATA_FILES = []
OPTIONS = {
    'iconfile': 'icon.icns',
    'includes': ['tkinter', 'pygame'],
    'semi_standalone': False,
    'site_packages': True,
    'alias': False,
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "pJing",
        'CFBundleIdentifier': "com.pJing",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Made by Farcas Nicu, Copyright © 2017"
    }
}

setup(
    app=APP,
    name='pJing',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)